### ISSUE TITLE
[500] Clerk is not a constructor

### ISSUE THREAD

**Issue by BlackBiM123** [wobsoriano/nuxt-clerk-template#11]
I am trying to switch from auth0 to clerk in my project, (Nuxt3) I do the analogy with the example and get an error 

[nuxt] [request error] [unhandled] [500] Clerk is not a constructor
  at Object.install (./node_modules/vue-clerk/dist/plugin.mjs:14:19)  
  at Object.use (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3744:18)  
  at ./plugins/clerk.ts:7:18  
  at ./node_modules/nuxt/dist/app/nuxt.js:112:60  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:156:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
  at ./node_modules/nuxt/dist/app/nuxt.js:158:56  
  at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:158:24)  
  at Object.runWithContext (./node_modules/nuxt/dist/app/nuxt.js:32:29)

Any thoughts in what direction to move, what to pay attention to? because I'm stuck.

**Comment by wobsoriano** [comment]
Did you add vue-clerk and clerk-js to your Nuxt’s build.transpile array? Check this project’s nuxt config!

**Comment by wobsoriano** [comment]
Feel free to reopen!

**Comment by BlackBiM123** [comment]
@wobsoriano No need for that, it was really about my inattention, thanks !
